<link rel="stylesheet" href="css/description.css">
<link rel="stylesheet" href="css/style.css">
</head>
<body>
<section class="description sec1">
	<div class="container">
		<div class="row">
			<h2 class="h2 text-center">
				Заголовок текста
			</h2>
		</div>
		<div class="row">
			<div class="col-md-3 col-sm-6 col-xs-12">
				<img src="image/skull.jpg" alt="" class="img-responsive img-rounded">
				<h4 class="h4 text-center">
					Описание
				</h4>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. A quae voluptas blanditiis adipisci similique laborum et aut commodi harum facilis dolorem at provident odit, iusto rem maxime, neque eos assumenda.
				</p>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique assumenda, deleniti. Praesentium amet, facere in perferendis cumque. Et nam a voluptates, repellendus aliquam, odio. Nobis obcaecati, odit non dolorum quia.
				</p>
				<button class="btn btn-default" type="button">
					Ознакомится
				</button>
			</div>
			<div class="col-md-3 col-sm-6 col-xs-12">
				<img src="image/skull.jpg" alt="" class="img-responsive img-rounded">
				<h4 class="h4 text-center">
					Описание
				</h4>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum rerum vitae maxime impedit praesentium deleniti, illo excepturi eius, nulla, at, qui est fugit facere recusandae quam voluptates! Totam quis, velit?
				</p>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestiae debitis eos necessitatibus, soluta explicabo, omnis, facilis labore at consequatur, aspernatur fuga est error assumenda. Dolor distinctio consequuntur aliquam cum ad.
				</p>
				<button class="btn btn-default" type="button">
					Ознакомится
				</button>
			</div>
			<div class="col-md-3 col-sm-6 col-xs-12">
				<img src="image/skull.jpg" alt="" class="img-responsive img-rounded">
				<h4 class="h4 text-center">
					Описание
				</h4>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam fugit, iusto corporis, ab iste excepturi at quas voluptas tempore blanditiis? Fugit vero ex excepturi quae, amet eveniet maiores necessitatibus deleniti.
				</p>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut non neque, earum ea aut debitis officia vel sit veritatis recusandae, optio quisquam, odit doloremque voluptate maxime inventore dolores nihil, quos.
				</p>
				<button class="btn btn-default" type="button">
					Ознакомится
				</button>
			</div>
			<div class="col-md-3 col-sm-6 col-xs-12">
				<img src="image/skull.jpg" alt="" class="img-responsive img-rounded">
				<h4 class="h4 text-center">
					Описание
				</h4>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi velit, libero dignissimos! Deserunt, culpa, eos necessitatibus omnis perferendis, libero ad alias dolorum repudiandae quis a ducimus assumenda quod voluptas.
				</p>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dolores, molestiae atque doloribus iure iusto reprehenderit, dicta accusamus nulla, ab veniam aliquam neque quia repellendus tempora excepturi accusantium quo modi.
				</p>
				<button class="btn btn-default" type="button">
					Ознакомится
				</button>
			</div>
		</div>
		<div class="row text-center">
			<div class="description-button">
				<button class="btn btn-success btn-lg" type="button">
					Кнопочка
				</button>
			</div>
		</div>
	</div>
</section>

<br>

<section class="description sec2">
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<img src="image/rock.jpg" alt="" class="img-responsive">
				<h4 class="h4 text-center"></h4>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate repudiandae, et incidunt voluptates animi, sunt delectus similique cumque saepe reprehenderit esse, accusantium, nisi eos ab voluptatibus impedit. Fugit voluptas, in!
				</p>
			</div>
			<div class="col-md-4">
				<img src="image/rock.jpg" alt="" class="img-responsive">
				<h4 class="h4 text-center"></h4>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae, nam in ipsum, amet quaerat, voluptas expedita asperiores repellat, obcaecati tempore voluptate sed eum! Excepturi, facere eum, cupiditate praesentium asperiores officia.
				</p>
			</div>
			<div class="col-md-4">
				<img src="image/rock.jpg" alt="" class="img-responsive">
				<h4 class="h4 text-center"></h4>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem laboriosam sit iusto vitae voluptatem quam esse, ipsam, fugiat facilis obcaecati nemo molestias similique cum odio unde illum commodi dicta assumenda.
				</p>
			</div>
		</div>
		<div class="row text-center">
			<div class="description-button">
				<button class="btn btn-success btn-lg" type="button">
					Кнопочка
				</button>
			</div>
		</div>
	</div>
</section>

<br>

<section class="description">
	<div class="container">
		<div class="row">
			<div class="col-md-3 col-md-offset-3">
				<img src="image/evolution.png" alt="" class="img-responsive">
				<h4 class="h4 text-center">
					Заголовок
				</h4>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum omnis odio quo, adipisci deserunt deleniti, exercitationem, nesciunt labore, nam sunt repellendus ratione maiores consectetur dolore iure provident sit porro quisquam.
				</p>
				<button class="btn btn-default" type="button">
					Ознакомится
				</button>
			</div>
			<div class="col-md-3">
				<img src="image/evolution.png" alt="" class="img-responsive">
				<h4 class="h4 text-center">
					Заголовок
				</h4>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta porro laborum ipsa earum sed ad, voluptas necessitatibus vel quis fugiat, sit eos quod magni amet explicabo reiciendis est esse! Repellendus.
				</p>
				<button class="btn btn-default" type="button">
					Ознакомится
				</button>
			</div>
		</div>
	</div>
</section>