<link rel="stylesheet" href="css/footers.css">
</head>
<body>
<section class="footers">
	<link href="https://fortawesome.github.io/Font-Awesome/assets/font-awesome/css/font-awesome.css" rel="stylesheet">
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-sm-6 footerleft ">
					<div class="logofooter">ЛОГО</div>
					<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley.</p>
					<p><i class="fa fa-map-pin"></i> адрес</p>
					<p><i class="fa fa-phone"></i> телефон</p>
					<p><i class="fa fa-envelope"></i> почта</p>
					
				</div>
				<div class="col-md-2 col-sm-6 paddingtop-bottom">
					<h6 class="heading7">заголовок</h6>
					<ul class="footer-ul">
						<li><a href="#"> ссылка</a></li>
						<li><a href="#"> ссылкаy</a></li>
						<li><a href="#"> ссылка</a></li>
						<li><a href="#"> ссылка</a></li>
						<li><a href="#"> ссылка</a></li>
						<li><a href="#"> ссылка</a></li>
						<li><a href="#"> ссылка</a></li>
					</ul>
				</div>
				<div class="col-md-3 col-sm-6 paddingtop-bottom">
					<h6 class="heading7">что то еще</h6>
					<div class="post">
						<p>непонятно <span>так себе</span></p>
						<p>непонятно <span>так себе</span></p>
						<p>непонятно <span>так себе</span></p>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 paddingtop-bottom">
					<div class="fb-page" data-href="" data-tabs="timeline" data-height="300" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
						<div class="fb-xfbml-parse-ignore">
							<blockquote cite=""><a href="">Facebook</a></blockquote>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<div class="copyright">
		<div class="container">
			<div class="col-md-6">
				<p>копирайт</p>
			</div>
			<div class="col-md-6">
				<ul class="bottom_ul">
					<li><a href="#">ссылка</a></li>
					<li><a href="#">ссылка</a></li>
					<li><a href="#">ссылка</a></li>
					<li><a href="#">ссылка</a></li>
					<li><a href="#">ссылка</a></li>
					<li><a href="#">ссылка</a></li>
				</ul>
			</div>
		</div>
	</div>
</section>

<br>


<section class="footers">
	<footer>
		<div class="container">
			<div class="row">
					<div class="col-md-4 col-sm-6 footerleft ">
						<div class="logofooter">ЛОГО</div>
						<p><i class="fa fa-map-pin"></i> адрес</p>
						<p><i class="fa fa-phone"></i> телефон</p>
						<p><i class="fa fa-envelope"></i> почта</p>
					
					</div>
				<div class="col-md-4 col-sm-6 paddingtop-bottom">
					<div class="post">
						<p>
							Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint ut voluptatibus velit totam porro itaque quibusdam, consequuntur, officia, assumenda excepturi harum, perferendis in nobis vel. Officia fugit neque ad maiores.
						</p>
					</div>
				</div>
				<div class="col-md-4 col-sm-6 coopyright">
					<h6 class="heading7">заголовок</h6>
					<div class="logofooter">ЛОГО</div>
				</div>
			</div>
		</div>
	</footer>
</section>


<br>
<section class="footers">
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-md-2 col-sm-6 footerleft text-center">
					<div class="logofooter">ЛОГО</div>
				</div>
				<div class="col-md-4 col-sm-6 paddingtop-bottom">
					<div class="post">
						<p>
							Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, veritatis, perspiciatis? 
						</p>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 pull-right paddingtop-bottom text-center">
					<div class="post">
						<h6 class="heading7">
							+7(999)999 99 99
						</h6>
						<button type="button" class="btn btn-default">Заказать</button>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 paddingtop-bottom text-center">
					<h6 class="heading7">Заголовок</h6>
					<div class="logofooter">
						ЛОГО
					</div>
				</div>
			</div>
		</div>
	</footer>
</section>