<link rel="stylesheet" href="css/info.css">
<link rel="stylesheet" href="css/style.css">
</head>
<body>
<section class="info sec1">
	<div class="container">
		<div class="row">
			<h2 class="text-center h2">
				Заголовок
			</h2>
		</div>
		<div class="row">
			<div class="b-info">
				<div class="col-md-6">
					<h4 class="text-center h4">
						Под заголовок для текста
					</h4>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempora totam, eaque, aspernatur non possimus ab dolor. Excepturi libero dolorum quam provident perferendis, voluptatibus expedita dicta consequatur magni. Ducimus incidunt, nam.
					</p>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci asperiores iure consequuntur aut, molestias cum! Eius quasi dignissimos nobis dolores maiores laborum animi labore modi alias fugit veritatis, atque dolor.
					</p>
				</div>
				<div class="col-md-6">
					<div class="b-info__form">
						<form action="">
							<h5 class="h5 text-center">
								Tекст для формы
							</h5>
							<div class="form-group">
								<input type="text" placeholder="Ваше имя">
							</div>
							<div class="form-group">
								<input type="text" placeholder="Ваш телефон">
							</div>
							<div class="form-group">
								<input type="text" placeholder="Ваш email">
							</div>
							<button type="button" class="btn btn-danger">Конопулька для формы</button>
						</form>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="b-info_bottom-button text-center">
				<button class="btn btn-primary" type="button">
					Нижняя кнопка 
				</button>
			</div>
		</div>
	</div>
</section>

<section class="info sec2">
	<div class="container">
		<div class="row">
			<h2 class="text-left">
				Заголовок страницы
			</h2>
		</div>
		<div class="row">
			<p class="text-center">
				<span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque tempora molestias fugit velit in, doloribus, ipsam sequi quia iste molestiae temporibus, quisquam minima labore sapiente aliquam atque eveniet porro dignissimos!</span><span>Consequatur quaerat, quia explicabo, alias corporis animi obcaecati quasi voluptatibus nulla sapiente commodi! Ex dolorem ut excepturi, explicabo ullam laborum deleniti, adipisci recusandae aliquam tempore amet fugit, laudantium pariatur itaque.</span>
			</p>
			<p class="text-center">
				<span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque tempora molestias fugit velit in, doloribus, ipsam sequi quia iste molestiae temporibus, quisquam minima labore sapiente aliquam atque eveniet porro dignissimos!</span><span>Consequatur quaerat, quia explicabo, alias corporis animi obcaecati quasi voluptatibus nulla sapiente commodi! Ex dolorem ut excepturi, explicabo ullam laborum deleniti, adipisci recusandae aliquam tempore amet fugit, laudantium pariatur itaque.</span>
			</p>
			<div class="b-info__form">
						<form action="">
							<h5 class="h5 text-center">
								Tекст для формы
							</h5>
							<div class="form-group">
								<input type="text" placeholder="Ваше имя">
							</div>
							<div class="form-group">
								<input type="text" placeholder="Ваш телефон">
							</div>
							<div class="form-group">
								<input type="text" placeholder="Ваш email">
							</div>
							<button type="button" class="btn btn-danger">Конопулька для формы</button>
						</form>
					</div>
		</div>
		<div class="row">
			<div class="b-info_bottom-button text-center">
				<button class="btn btn-primary" type="button">
					Нижняя кнопка 
				</button>
			</div>
		</div>
	</div>
</section>

<section class="info sec3">
	<div class="container">
		<div class="row">
			<h2 class="h2 text-center">
				Заголовок текста
			</h2>
			<p class="text-center p-mini">
				Под заголовок заголовка
			</p>
		</div>
		<div class="row">
			<div class="b-info__form">
						<form action="">
							<h5 class="h5 text-center">
								Tекст для формы
							</h5>
							<div class="form-group">
								<input type="text" placeholder="Ваше имя">
							</div>
							<div class="form-group">
								<input type="text" placeholder="Ваш телефон">
							</div>
							<div class="form-group">
								<input type="text" placeholder="Ваш email">
							</div>
							<button type="button" class="btn btn-danger">Конопулька для формы</button>
						</form>
					</div>
		</div>
		</div>
	</div>
</section>

<section class="info sec4">
	<div class="container">
		<div class="row">
			<h2 class="text-center h2">
				Заголовк текста
			</h2>
		</div>
		<div class="row">
			<div class="col-md-6">
				<div class="b-info__form">
						<form action="">
							<h5 class="h5 text-center">
								Tекст для формы
							</h5>
							<div class="form-group">
								<input type="text" placeholder="Ваше имя">
							</div>
							<div class="form-group">
								<input type="text" placeholder="Ваш телефон">
							</div>
							<div class="form-group">
								<input type="text" placeholder="Ваш email">
							</div>
							<button type="button" class="btn btn-danger">Конопулька для формы</button>
						</form>
					</div>
			</div>
			<div class="col-md-6">
				<h5 class="h5 text-left">
					Маленький подзаголовок
				</h5>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia vero sit, officiis voluptates minima sapiente laboriosam quis quibusdam quam ex animi nostrum, veniam consequatur. Maxime dignissimos voluptates ullam quod dolor!
					</p>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum, voluptate, ad. Consequuntur corrupti aliquam nulla architecto commodi obcaecati? Eum eveniet, adipisci dicta dolorum ea repudiandae doloribus id earum numquam! Minus.
					</p>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium aut quam expedita? Ad assumenda, voluptates illo nam corporis placeat sint nemo perferendis consequuntur facilis nihil quaerat voluptate minus, autem, officia!
					</p>
			</div>
		</div>
	</div>
</section>

<section class="info sec5">
	<div class="container">
		<div class="row">
			<h2 class="text-center h2">
				Заголовок для текста
			</h2>
		</div>
		<div class="row">
			<div class="col-md-12">
				<!-- <div class="col-md-4">
					<div class="b-info__form">
						<form action="">
							<h5 class="h5 text-center">
								Tекст для формы
							</h5>
							<div class="form-group">
								<input type="text" placeholder="Ваше имя">
							</div>
							<div class="form-group">
								<input type="text" placeholder="Ваш телефон">
							</div>
							<div class="form-group">
								<input type="text" placeholder="Ваш email">
							</div>
							<button type="button" class="btn btn-danger">Конопулька для формы</button>
						</form>
					</div>
				</div> -->
				<div class="col-md-8 col-md-offset-2 text-center">
					<p class="paragraf-top">
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex provident ducimus, minima voluptas veniam optio! Voluptatem, magnam mollitia commodi vero neque soluta perspiciatis reiciendis vel optio omnis. Hic minima, maxime.
					</p>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui, ea ut modi praesentium tempore autem aspernatur, suscipit quasi eius debitis corporis dolorum harum, rem! Quam sapiente cumque accusantium consequatur voluptatibus?
					</p>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam voluptatem nisi, dignissimos culpa deleniti distinctio repellendus eveniet odio facere eos esse neque beatae tempora cupiditate eaque quibusdam! Praesentium, rem, odio.
					</p>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum magni totam debitis iste cum quibusdam itaque corporis vitae veniam ad, est aliquam a voluptate consectetur similique, quas ut, perspiciatis facere?
					</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="b-info_bottom-button text-center">
				<button class="btn btn-primary" type="button">
					Нижняя кнопка 
				</button>
			</div>
		</div>
	</div>
</section>

<section class="info sec6">
	<div class="container">
		<div class="row">
			<h2 class="h2 text-center">
				Заголовок текста
			</h2>
		</div>
		<div class="row">
			<p class="paragraf-top">
				<span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut perspiciatis officiis, facere. Illum culpa maiores voluptate dolorem necessitatibus aperiam? Rerum, eligendi. Ipsam excepturi at, adipisci libero sunt aperiam et, voluptatem!</span>
				<span>Animi harum quam suscipit culpa tempore laudantium neque. Repellat perspiciatis explicabo cupiditate nihil, consequuntur a velit, ab recusandae obcaecati doloremque aperiam blanditiis perferendis mollitia qui! Aperiam, hic dolore tempore harum.</span>
				<span>Debitis omnis ipsum ipsam voluptas quisquam voluptates esse dolor amet, repudiandae voluptatem veniam sed, et soluta porro, consequatur voluptate praesentium! Alias, ex, quia. Provident doloremque quasi consectetur accusantium, voluptate laboriosam.</span>
				<span>Eligendi quaerat dolore impedit saepe quod consequatur consequuntur tempore iusto assumenda, minus dignissimos dolorem quisquam praesentium excepturi rerum distinctio vel ab blanditiis illo perferendis officiis illum. Perferendis expedita, odio velit.</span>
				<span>Repellat laborum veniam molestias tempora nulla adipisci, hic reiciendis earum esse quas maxime asperiores dolores, quod aliquam voluptatem libero. Nisi consequatur illo iste deserunt voluptas esse similique aut minus, debitis?</span>
			</p>
		</div>
		<div class="row">
			<div class="b-info_form-inline">
				<h4 class="h4 text-center">
					Заголовок для формы
				</h4>
				<form action="" class="form-inline">
					<div class="group-form_i">
						<input type="text" placeholder="Ваше имя">
					</div>
					<div class="group-form_i">
						<input type="text" placeholder="Ваш телефон">
					</div>
					<div class="group-form_i">
						<input type="text" placeholder="Ваш email">
					</div>
					<button class="btn btn-info" type="button">Отправить</button>
				</form>
			</div>
		</div>
	</div>
</section>