<link rel="stylesheet" href="css/mega-nav.css">
</head>
<body>
<section class="mega-nav">
	<div class="container">
	  <nav class="navbar navbar-inverse">
	    <div class="navbar-header">
	    	<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".js-navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">ЛОГОТИП</a>
		</div>
		
		<div class="collapse navbar-collapse js-navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="dropdown mega-dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Чувак <span class="caret"></span></a>				
					<ul class="dropdown-menu mega-dropdown-menu">
						<li class="col-sm-3">
							<ul>
								<li class="dropdown-header">Чувак1</li>                            
	                            <div id="menCollection" class="carousel slide" data-ride="carousel">
	                              <div class="carousel-inner">
	                                <div class="item active">
	                                    <a href="#"><img src="http://placehold.it/254x150/ff3546/f5f5f5/&text=New+Collection" class="img-responsive" alt="product 1"></a>
	                                    <h4><small>Лето </small></h4>                                        
	                                    <button class="btn btn-primary" type="button">49р</button> <button href="#" class="btn btn-default" type="button"><span class="glyphicon glyphicon-heart"></span> кнопка</button>       
	                                </div><!-- End Item -->
	                                <div class="item">
	                                    <a href="#"><img src="http://placehold.it/254x150/3498db/f5f5f5/&text=New+Collection" class="img-responsive" alt="product 2"></a>
	                                    <h4><small>Золото</small></h4>                                        
	                                    <button class="btn btn-primary" type="button">90р</button> <button href="#" class="btn btn-default" type="button"><span class="glyphicon glyphicon-heart"></span> кнопка</button>        
	                                </div><!-- End Item -->
	                                <div class="item">
	                                    <a href="#"><img src="http://placehold.it/254x150/2ecc71/f5f5f5/&text=New+Collection" class="img-responsive" alt="product 3"></a>
	                                    <h4><small>еще что то</small></h4>                                        
	                                    <button class="btn btn-primary" type="button">79 р</button> <button href="#" class="btn btn-default" type="button"><span class="glyphicon glyphicon-heart"></span> кнопка</button>      
	                                </div><!-- End Item -->                                
	                              </div><!-- End Carousel Inner -->
	                              <!-- Controls -->
	                              <a class="left carousel-control" href="#menCollection" role="button" data-slide="prev">
	                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	                                <span class="sr-only">пред</span>
	                              </a>
	                              <a class="right carousel-control" href="#menCollection" role="button" data-slide="next">
	                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	                                <span class="sr-only">след</span>
	                              </a>
	                            </div><!-- /.carousel -->
	                            <li class="divider"></li>
	                            <li><a href="#">коллекция <span class="glyphicon glyphicon-chevron-right pull-right"></span></a></li>
							</ul>
						</li>
						<li class="col-sm-3">
							<ul>
								<li class="dropdown-header">описалка</li>
								<li><a href="#">авто каруселька</a></li>
	                            <li><a href="#">кнопка карусельки</a></li>
	                            <li><a href="#">лево и право</a></li>
								<li><a href="#">еще ччто то</a></li>
								<li class="divider"></li>
								<li class="dropdown-header">фигня</li>
	                            <li><a href="#">глифы</a></li>
								<li><a href="#">шрифт</a></li>
							</ul>
						</li>
						<li class="col-sm-3">
							<ul>
								<li class="dropdown-header">бла бла</li>
								<li><a href="#">бла бла бла</a></li>
								<li><a href="#">бла бла бла</a></li>
								<li><a href="#">бла бла бла</a></li>                            
								<li><a href="#">бла бла бла</a></li>							
							</ul>
						</li>
						<li class="col-sm-3">
							<ul>
								<li class="dropdown-header">бла бла </li>
	                            <li><a href="#">ссылка</a></li>
								<li><a href="#">ссылка</a></li>
								<li><a href="#">ссылка</a></li>
								<li><a href="#">ссылка</a></li>                         
							</ul>
						</li>
					</ul>				
				</li>
	            <li class="dropdown mega-dropdown">
	    			<a href="#" class="dropdown-toggle" data-toggle="dropdown">текст <span class="caret"></span></a>				
					<ul class="dropdown-menu mega-dropdown-menu">
						<li class="col-sm-3">
	    					<ul>
								<li class="dropdown-header">блабла </li>
								<li><a href="#">ссылка</a></li>
	                            <li><a href="#">ссылка</a></li>
	                            <li><a href="#">ссылка</a></li>
								<li><a href="#">ссылка</a></li>
								<li class="divider"></li>
								<li class="dropdown-header">блаблабла </li>
	                            <li><a href="#">ссылка</a></li>
								<li><a href="#">ссылка</a></li>
							</ul>
						</li>
						<li class="col-sm-3">
							<ul>
								<li class="dropdown-header">блабла</li>
								<li><a href="#">ссылка</a></li>
								<li><a href="#">ссылка</a></li>
								<li><a href="#">ссылка</a></li>                            
								<li><a href="#">ссылка</a></li>							
							</ul>
						</li>
						<li class="col-sm-3">
							<ul>
								<li class="dropdown-header">так что нибудь</li>
	                            <li><a href="#">так что нибудь</a></li>
								<li><a href="#">так что нибудь</a></li>
								<li><a href="#">так что нибудь</a></li>
								<li><a href="#">так что нибудь</a></li>                         
							</ul>
						</li>
	                    <li class="col-sm-3">
	    					<ul>
								<li class="dropdown-header">ерунда</li>                            
	                            <div id="womenCollection" class="carousel slide" data-ride="carousel">
	                              <div class="carousel-inner">
	                                <div class="item active">
	                                    <a href="#"><img src="http://placehold.it/254x150/3498db/f5f5f5/&text=New+Collection" class="img-responsive" alt="product 1"></a>
	                                    <h4><small>что нибудь </small></h4>                                        
	                                    <button class="btn btn-primary" type="button">49р</button> <button href="#" class="btn btn-default" type="button"><span class="glyphicon glyphicon-heart"></span> что нибудь</button>       
	                                </div><!-- End Item -->
	                                <div class="item">
	                                    <a href="#"><img src="http://placehold.it/254x150/ff3546/f5f5f5/&text=New+Collection" class="img-responsive" alt="product 2"></a>
	                                    <h4><small>какой то загловок</small></h4>                                        
	                                    <button class="btn btn-primary" type="button">9р</button> <button href="#" class="btn btn-default" type="button"><span class="glyphicon glyphicon-heart"></span> конопулька</button>        
	                                </div><!-- End Item -->
	                                <div class="item">
	                                    <a href="#"><img src="http://placehold.it/254x150/2ecc71/f5f5f5/&text=New+Collection" class="img-responsive" alt="product 3"></a>
	                                    <h4><small>бред</small></h4>                                        
	                                    <button class="btn btn-primary" type="button">49р</button> <button href="#" class="btn btn-default" type="button"><span class="glyphicon glyphicon-heart"></span> конопулька</button>      
	                                </div><!-- End Item -->                                
	                              </div><!-- End Carousel Inner -->
	                              <!-- Controls -->
	                              <a class="left carousel-control" href="#womenCollection" role="button" data-slide="prev">
	                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	                                <span class="sr-only">след</span>
	                              </a>
	                              <a class="right carousel-control" href="#womenCollection" role="button" data-slide="next">
	                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	                                <span class="sr-only">пред</span>
	                              </a>
	                            </div><!-- /.carousel -->
	                            <li class="divider"></li>
	                            <li><a href="#">показ <span class="glyphicon glyphicon-chevron-right pull-right"></span></a></li>
							</ul>
						</li>
					</ul>				
				</li>
	            <li><a href="#">текст</a></li>
			</ul>
	        <ul class="nav navbar-nav navbar-right">
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">мой аккаунт <span class="caret"></span></a>
	          <ul class="dropdown-menu" role="menu">
	            <li><a href="#">ссылка</a></li>
	            <li><a href="#">ссылка</a></li>
	            <li><a href="#">ссылка</a></li>
	            <li class="divider"></li>
	            <li><a href="#">ссылка</a></li>
	          </ul>
	        </li>
	        <li><a href="#">карта (0) </a></li>
	      </ul>
		</div><!-- /.nav-collapse -->
	  </nav>
	</div>
</section>