<link rel="stylesheet" href="css/price.css">
</head>
<body>
<section class="price">
	<div class="container">
		<div class="row text-center">
			<div class="col-md-12">
				<br/><br/>
				<h3>
					Наши расценки
				</h3>
			</div>
		</div>
		
		<div class="row db-padding-btm db-attached">
			<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
				<div class="db-wrapper">
					<div class="db-pricing-eleven db-bk-color-one">
						<div class="price">
							<sup>р</sup>99
							<small>за квартал</small>
						</div>
						<div class="type">
							BASIC
						</div>
						<ul>
							<li><i class="glyphicon glyphicon-print"></i>30+ аккаунт </li>
							<li><i class="glyphicon glyphicon-time"></i>150+ проект </li>
							<li><i class="glyphicon glyphicon-trash"></i>Требуется</li>
						</ul>
						<div class="pricing-footer">
							<a href="#" class="btn db-button-color-square btn-lg">Заказать</a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
				<div class="db-wrapper">
					<div class="db-pricing-eleven db-bk-color-two popular">
						<div class="price">
							<sup>р</sup>199
							<small>за месяц</small>
						</div>
						<div class="type">
							MEDIUM
						</div>
						<ul>
							<li><i class="glyphicon glyphicon-print"></i>30+ аккаунт </li>
							<li><i class="glyphicon glyphicon-time"></i>150+ проект </li>
							<li><i class="glyphicon glyphicon-trash"></i>Lead требуется</li>
						</ul>
						<div class="pricing-footer">
							<a href="#" class="btn db-button-color-square btn-lg">Заказать</a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
				<div class="db-wrapper">
					<div class="db-pricing-eleven db-bk-color-three">
						<div class="price">
							<sup>р</sup>249
							<small>за месяц</small>
						</div>
						<div class="type">
							ADVANCE
						</div>
						<ul>
							<li><i class="glyphicon glyphicon-print"></i>30+ аккаунт </li>
							<li><i class="glyphicon glyphicon-time"></i>150+ проект </li>
							<li><i class="glyphicon glyphicon-trash"></i>Lead требуется</li>
						</ul>
						<div class="pricing-footer">
							<a href="#" class="btn db-button-color-square btn-lg">Заказать</a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
				<div class="db-wrapper">
					<div class="db-pricing-eleven db-bk-color-six">
						<div class="price">
							<sup>р</sup>599
							<small>за месяц</small>
						</div>
						<div class="type">
							EXTENDED
						</div>
						<ul>
							<li><i class="glyphicon glyphicon-print"></i>30+ аккаунт </li>
							<li><i class="glyphicon glyphicon-time"></i>150+ проект </li>
							<li><i class="glyphicon glyphicon-trash"></i>Lead требуется</li>
						</ul>
						<div class="pricing-footer">
							<a href="#" class="btn db-button-color-square btn-lg">Заказать</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row db-padding-btm db-attached">
			<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
				<div class="db-wrapper">
					<div class="db-pricing-eleven db-bk-color-one">
						<div class="price">
							<sup>р</sup>99
							<small>за месяц</small>
						</div>
						<div class="type">
							SMALL
						</div>
						<ul>
							<li><i class="glyphicon glyphicon-print"></i>30+ аккаунт </li>
							<li><i class="glyphicon glyphicon-time"></i>150+ проект </li>
							<li><i class="glyphicon glyphicon-trash"></i>Lead требуется</li>
						</ul>
						<div class="pricing-footer">
							<a href="#" class="btn db-button-color-square btn-lg">Заказать</a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
				<div class="db-wrapper">
					<div class="db-pricing-eleven db-bk-color-two popular">
						<div class="price">
							<sup>р</sup>159
							<small>за месяц</small>
						</div>
						<div class="type">
							MEDIUM
						</div>
						<ul>
							<li><i class="glyphicon glyphicon-print"></i>30+ аккаунт </li>
							<li><i class="glyphicon glyphicon-time"></i>150+ проект </li>
							<li><i class="glyphicon glyphicon-trash"></i>Lead требуется</li>
						</ul>
						<div class="pricing-footer">
							<a href="#" class="btn db-button-color-square btn-lg">Заказать</a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
				<div class="db-wrapper">
					<div class="db-pricing-eleven db-bk-color-three">
						<div class="price">
							<sup>р</sup>799
							<small>за месяц</small>
						</div>
						<div class="type">
							ADVANCE
						</div>
						<ul>
							<li><i class="glyphicon glyphicon-print"></i>30+ аккаунт </li>
							<li><i class="glyphicon glyphicon-time"></i>150+ проект </li>
							<li><i class="glyphicon glyphicon-trash"></i>Lead требуется</li>
						</ul>
						<div class="pricing-footer">
							<a href="#" class="btn db-button-color-square btn-lg">Заказать</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</section>