<link rel="stylesheet" href="css/reviews.css">
</head>
<body>
<section class="reviews">
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<h3>отзыв</h3>
			</div><!-- /col-sm-12 -->
		</div><!-- /row -->
		<div class="row">
			<div class="col-sm-1">
				<div class="thumbnail">
					<img class="img-responsive user-photo" src="image/user.jpg">
				</div><!-- /thumbnail -->
			</div><!-- /col-sm-1 -->
			<div class="col-sm-5">
				<div class="panel panel-default">
					<div class="panel-heading">
						<strong>юзер</strong> <span class="text-muted">коммент</span>
					</div>
					<div class="panel-body">
						панель
					</div><!-- /panel-body -->
				</div><!-- /panel panel-default -->
			</div><!-- /col-sm-5 -->
			<div class="col-sm-1">
				<div class="thumbnail">
					<img class="img-responsive user-photo" src="image/user.jpg">
				</div><!-- /thumbnail -->
			</div><!-- /col-sm-1 -->
			<div class="col-sm-5">
				<div class="panel panel-default">
					<div class="panel-heading">
						<strong>юзер</strong>
						<span class="text-muted">комент</span>
					</div>
					<div class="panel-body">
						панель
					</div><!-- /panel-body -->
				</div><!-- /panel panel-default -->
			</div><!-- /col-sm-5 -->
		</div><!-- /row -->
	</div><!-- /container -->
</section>


<section class="reviews">
	<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h2 class="page-header">ОТЗЫВЫ</h2>
        <section class="comment-list">
          <!-- First Comment -->
          <article class="row">
            <div class="col-md-2 col-sm-2 hidden-xs">
              <figure class="thumbnail">
                <img class="img-responsive" src="image/user.jpg" />
                <figcaption class="text-center">ИМЯ</figcaption>
              </figure>
            </div>
            <div class="col-md-10 col-sm-10">
              <div class="panel panel-default arrow left">
                <div class="panel-body">
                  <header class="text-left">
                    <div class="comment-user"><i class="fa fa-user"></i> бла</div>
                    <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i> дек 16, 2015</time>
                  </header>
                  <div class="comment-post">
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    </p>
                  </div>
                  
                </div>
              </div>
            </div>
          </article>
          <!-- Second Comment Reply -->
          <article class="row">
            <div class="col-md-2 col-sm-2 col-md-offset-1 col-sm-offset-0 hidden-xs">
              <figure class="thumbnail">
                <img class="img-responsive" src="image/user.jpg" />
                <figcaption class="text-center">юзер</figcaption>
              </figure>
            </div>
            <div class="col-md-9 col-sm-9">
              <div class="panel panel-default arrow left">
                <div class="panel-body">
                  <header class="text-left">
                    <div class="comment-user"><i class="fa fa-user"></i> дата</div>
                    <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i> дек 16, 2015</time>
                  </header>
                  <div class="comment-post">
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </article>
          <!-- Third Comment -->
          <article class="row">
            <div class="col-md-10 col-sm-10">
              <div class="panel panel-default arrow right">
                <div class="panel-body">
                  <header class="text-right">
                    <div class="comment-user"><i class="fa fa-user"></i> дата</div>
                    <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i> дек 16, 2015</time>
                  </header>
                  <div class="comment-post">
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-2 col-sm-2 hidden-xs">
              <figure class="thumbnail">
                <img class="img-responsive" src="image/user.jpg" />
                <figcaption class="text-center">юзер</figcaption>
              </figure>
            </div>
          </article>
          <!-- Fourth Comment -->
          <article class="row">
            <div class="col-md-2 col-sm-2 hidden-xs">
              <figure class="thumbnail">
                <img class="img-responsive" src="image/user.jpg" />
                <figcaption class="text-center">юзер</figcaption>
              </figure>
            </div>
            <div class="col-md-10 col-sm-10 col-xs-12">
              <div class="panel panel-default arrow left">
                <div class="panel-body">
                  <header class="text-left">
                    <div class="comment-user"><i class="fa fa-user"></i> дата</div>
                    <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i> дек 16, 2015</time>
                  </header>
                  <div class="comment-post">
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </article>
          <!-- Fifth Comment -->
          <article class="row">
            <div class="col-md-10 col-sm-10">
              <div class="panel panel-default arrow right">
                <div class="panel-body">
                  <header class="text-right">
                    <div class="comment-user"><i class="fa fa-user"></i> дата</div>
                    <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i> дек 16, 2015</time>
                  </header>
                  <div class="comment-post">
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-2 col-sm-2 hidden-xs">
              <figure class="thumbnail">
                <img class="img-responsive" src="image/user.jpg" />
                <figcaption class="text-center">юзер</figcaption>
              </figure>
            </div>
          </article>
          <!-- Sixth Comment Reply -->
          <article class="row">
            <div class="col-md-9 col-sm-9 col-md-offset-1 col-md-pull-1 col-sm-offset-0">
              <div class="panel panel-default arrow right">
                <div class="panel-body">
                  <header class="text-right">
                    <div class="comment-user"><i class="fa fa-user"></i> дата</div>
                    <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i> дек 16, 2015</time>
                  </header>
                  <div class="comment-post">
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-2 col-sm-2 col-md-pull-1 hidden-xs">
              <figure class="thumbnail">
                <img class="img-responsive" src="image/user.jpg" />
                <figcaption class="text-center">юзер</figcaption>
              </figure>
            </div>
          </article>
        </section>
    </div>
  </div>
</div>

</section>


<section class="reviews">
	<div class="container">
	<div class="row">
		<h2>отзывы </h2>
	</div>
</div>
<div class="carousel-reviews broun-block">
    <div class="container">
        <div class="row">
            <div id="carousel-reviews" class="carousel slide" data-ride="carousel">
            
                <div class="carousel-inner">
                    <div class="item active">
                	    <div class="col-md-4 col-sm-6">
        				    <div class="block-text rel zmin">
						        <a title="" href="#">МАГАЗИН</a>
							    <div class="mark">рейтинг <span class="rating-input"><span data-value="0" class="glyphicon glyphicon-star"></span><span data-value="1" class="glyphicon glyphicon-star"></span><span data-value="2" class="glyphicon glyphicon-star"></span><span data-value="3" class="glyphicon glyphicon-star"></span><span data-value="4" class="glyphicon glyphicon-star-empty"></span><span data-value="5" class="glyphicon glyphicon-star-empty"></span>  </span></div>
						        <p>
						        	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni ex laboriosam, sapiente ducimus est quisquam id ratione autem assumenda in a quaerat atque, eius iste minus dolores sint officia, consequuntur!
						        </p>
							    <ins class="ab zmin sprite sprite-i-triangle block"></ins>
					        </div>
							<div class="person-text rel">
				                <img src="image/women.png" class="img-responsive img-circle">
								<a title="" href="#">АННА</a>
								<i>МОСКВА</i>
							</div>
						</div>
            			<div class="col-md-4 col-sm-6 hidden-xs">
						    <div class="block-text rel zmin">
						        <a title="" href="#">АРХИВ</a>
							    <div class="mark">Рейтинг <span class="rating-input"><span data-value="0" class="glyphicon glyphicon-star"></span><span data-value="1" class="glyphicon glyphicon-star"></span><span data-value="2" class="glyphicon glyphicon-star-empty"></span><span data-value="3" class="glyphicon glyphicon-star-empty"></span><span data-value="4" class="glyphicon glyphicon-star-empty"></span><span data-value="5" class="glyphicon glyphicon-star-empty"></span>  </span></div>
        						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque animi ut magni a aliquid vero earum quos, natus molestiae assumenda accusamus quod aut quo obcaecati iure commodi enim, dolores illum.</p>
					            <ins class="ab zmin sprite sprite-i-triangle block"></ins>
				            </div>
							<div class="person-text rel">
				                <img src="image/img14.png" alt="" class="img-responsive img-circle">
						        <a title="" href="#">РОМАН</a>
								<i>КАЗАНЬ</i>
							</div>
						</div>
						<div class="col-md-4 col-sm-6 hidden-sm hidden-xs">
							<div class="block-text rel zmin">
								<a title="" href="#">Блогер</a>
								<div class="mark">Рейтинг <span class="rating-input"><span data-value="0" class="glyphicon glyphicon-star"></span><span data-value="1" class="glyphicon glyphicon-star"></span><span data-value="2" class="glyphicon glyphicon-star"></span><span data-value="3" class="glyphicon glyphicon-star"></span><span data-value="4" class="glyphicon glyphicon-star"></span><span data-value="5" class="glyphicon glyphicon-star"></span>  </span></div>
    							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum cumque fugiat ipsum quam sunt ab. Explicabo obcaecati, at ullam eos beatae consectetur consequatur, doloremque perferendis maxime quae deserunt non debitis!</p>
								<ins class="ab zmin sprite sprite-i-triangle block"></ins>
							</div>
							<div class="person-text rel">
								<img src="image/img15.png" alt="" calss="img-responsive img-circle">
								<a title="" href="#">ЮЗЕР</a>
								<i>САРАТОВ</i>
							</div>
						</div>
                    </div>
                    <div class="item">
                        <div class="col-md-4 col-sm-6">
        				    <div class="block-text rel zmin">
						        <a title="" href="#">ЬАГАЗИН</a>
							    <div class="mark">Рейтинг <span class="rating-input"><span data-value="0" class="glyphicon glyphicon-star"></span><span data-value="1" class="glyphicon glyphicon-star"></span><span data-value="2" class="glyphicon glyphicon-star"></span><span data-value="3" class="glyphicon glyphicon-star"></span><span data-value="4" class="glyphicon glyphicon-star-empty"></span><span data-value="5" class="glyphicon glyphicon-star-empty"></span>  </span></div>
						        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro delectus ipsam accusantium. Quas eligendi, necessitatibus impedit quod quis voluptatum, nostrum excepturi. Animi a, veritatis blanditiis ea magnam explicabo nisi dolor.</p>
							    <ins class="ab zmin sprite sprite-i-triangle block"></ins>
					        </div>
							<div class="person-text rel">
								<img alt="" src="image/women.png" class="img-responsive img-circle">
								<a title="" href="#">АННА</a>
								<i>МОСКВА</i>
							</div>
						</div>
            			<div class="col-md-4 col-sm-6 hidden-xs">
						    <div class="block-text rel zmin">
						        <a title="" href="#">АРХИВ</a>
							    <div class="mark">Рейтинг <span class="rating-input"><span data-value="0" class="glyphicon glyphicon-star"></span><span data-value="1" class="glyphicon glyphicon-star"></span><span data-value="2" class="glyphicon glyphicon-star-empty"></span><span data-value="3" class="glyphicon glyphicon-star-empty"></span><span data-value="4" class="glyphicon glyphicon-star-empty"></span><span data-value="5" class="glyphicon glyphicon-star-empty"></span>  </span></div>
        						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam soluta, quia adipisci at officiis tempore suscipit consequatur. Ad ab cum nesciunt. Fugiat consequatur deleniti sequi nisi aperiam facere quos, aspernatur!</p>
					            <ins class="ab zmin sprite sprite-i-triangle block"></ins>
				            </div>
							<div class="person-text rel">
								<img alt="" src="image/img14.png">
						        <a title="" href="#">РОМАН</a>
								<i>КАЗАНЬ</i>
							</div>
						</div>
						<div class="col-md-4 col-sm-6 hidden-sm hidden-xs">
							<div class="block-text rel zmin">
								<a title="" href="#">БЛОГЕР</a>
								<div class="mark">Рейтинг <span class="rating-input"><span data-value="0" class="glyphicon glyphicon-star"></span><span data-value="1" class="glyphicon glyphicon-star"></span><span data-value="2" class="glyphicon glyphicon-star"></span><span data-value="3" class="glyphicon glyphicon-star"></span><span data-value="4" class="glyphicon glyphicon-star"></span><span data-value="5" class="glyphicon glyphicon-star"></span>  </span></div>
    							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos possimus quas velit. Saepe ab suscipit, optio similique blanditiis voluptatem obcaecati perferendis assumenda earum minima inventore. Commodi aperiam eaque deserunt nam!</p>
								<ins class="ab zmin sprite sprite-i-triangle block"></ins>
							</div>
							<div class="person-text rel">
								<img alt="" src="image/img15.png">
								<a title="" href="#">ЮЗЕР</a>
								<i>САРАТОВ</i>
							</div>
						</div>
                    </div>
                    <div class="item">
                        <div class="col-md-4 col-sm-6">
        				    <div class="block-text rel zmin">
						        <a title="" href="#">ЬАГАЗИН</a>
							    <div class="mark">Рейтинг <span class="rating-input"><span data-value="0" class="glyphicon glyphicon-star"></span><span data-value="1" class="glyphicon glyphicon-star"></span><span data-value="2" class="glyphicon glyphicon-star"></span><span data-value="3" class="glyphicon glyphicon-star"></span><span data-value="4" class="glyphicon glyphicon-star-empty"></span><span data-value="5" class="glyphicon glyphicon-star-empty"></span>  </span></div>
						        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus eos eum optio natus blanditiis! Dolor assumenda nulla atque molestias non accusamus cum necessitatibus, possimus minima libero, omnis praesentium. Deleniti, fugit.</p>
							    <ins class="ab zmin sprite sprite-i-triangle block"></ins>
					        </div>
							<div class="person-text rel">
								<img alt="" src="image/img14.png">
								<a title="" href="#">АННА</a>
								<i>МОСКВА</i>
							</div>
						</div>
            			<div class="col-md-4 col-sm-6 hidden-xs">
						    <div class="block-text rel zmin">
						        <a title="" href="#">АРХИВ</a>
							    <div class="mark">Рейтинг <span class="rating-input"><span data-value="0" class="glyphicon glyphicon-star"></span><span data-value="1" class="glyphicon glyphicon-star"></span><span data-value="2" class="glyphicon glyphicon-star-empty"></span><span data-value="3" class="glyphicon glyphicon-star-empty"></span><span data-value="4" class="glyphicon glyphicon-star-empty"></span><span data-value="5" class="glyphicon glyphicon-star-empty"></span>  </span></div>
        						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam, temporibus porro dolore rem error laudantium culpa voluptatibus cumque aspernatur fugiat illum sunt itaque aliquam ex omnis officia laborum! Consequatur, placeat. </p>
					            <ins class="ab zmin sprite sprite-i-triangle block"></ins>
				            </div>
							<div class="person-text rel">
								<img alt="" src="image/img14.png">
						        <a title="" href="#">Роман</a>
								<i>КАЗАНЬ</i>
							</div>
						</div>
						<div class="col-md-4 col-sm-6 hidden-sm hidden-xs">
							<div class="block-text rel zmin">
								<a title="" href="#">БЛОГЕР</a>
								<div class="mark">Рейтинг <span class="rating-input"><span data-value="0" class="glyphicon glyphicon-star"></span><span data-value="1" class="glyphicon glyphicon-star"></span><span data-value="2" class="glyphicon glyphicon-star"></span><span data-value="3" class="glyphicon glyphicon-star"></span><span data-value="4" class="glyphicon glyphicon-star"></span><span data-value="5" class="glyphicon glyphicon-star"></span>  </span></div>
    							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum eaque praesentium voluptates velit a est corporis! Asperiores exercitationem molestiae rerum, dolores animi commodi aspernatur. Nostrum voluptate repudiandae quod ratione quis.</p>
								<ins class="ab zmin sprite sprite-i-triangle block"></ins>
							</div>
							<div class="person-text rel">
								<img alt="" src="http://myinstantcms.ru/images/img15.png">
								<a title="" href="#">Юзер</a>
								<i>САРАТОВ</i>
							</div>
						</div>
                    </div>                    
                </div>
                <a class="left carousel-control" href="#carousel-reviews" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-reviews" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>
    </div>
</div>
</section>