<link rel="stylesheet" href="css/steps.css">
</head>
<body>
<section class="steps">
	<div class="container">
		<div class="row text-center">
		<h2 class="h2">
			Этапы
		</h2>
			<div class="col-md-2 col-md-offset-1 img-circle">
				<div class="b-steps">
					<span class="span">2</span>
				</div>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
				</p>
			</div>
			<div class="col-md-2 img-circle">
				<div class="b-steps">
					<span class="span">2</span>
				</div>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
				</p>
			</div>
			<div class="col-md-2 img-circle">
				<div class="b-steps">
					<span class="span">2</span>
				</div>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
				</p>
			</div>
			<div class="col-md-2 img-circle">
				<div class="b-steps">
					<span class="span">2</span>
				</div>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
				</p>
			</div>
			<div class="col-md-2 img-circle">
				<div class="b-steps">
					<span class="span">2</span>
				</div>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
				</p>
			</div>
		</div>
	</div>
</section>